"use client";

import React, { useState, useEffect } from 'react';
import { FileText, Download, Copy, Check, Code } from 'lucide-react';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { vscDarkPlus } from 'react-syntax-highlighter/dist/esm/styles/prism';

interface FilePreviewProps {
    filePath: string;
    fileName: string;
    workspaceId: string;
}

export default function FilePreview({ filePath, fileName, workspaceId }: FilePreviewProps) {
    const [content, setContent] = useState<string>('');
    const [loading, setLoading] = useState(false);
    const [copied, setCopied] = useState(false);

    useEffect(() => {
        loadFile();
    }, [filePath]);

    const loadFile = async () => {
        setLoading(true);
        try {
            // Mock content - replace with actual API call
            const mockContent = `# Generated by Autonomous Agent

def calculator(a, b, operation):
    """
    Performs basic arithmetic operations.
    
    Args:
        a (float): First number
        b (float): Second number
        operation (str): Operation (+, -, *, /)
    
    Returns:
        float: Result of operation
    """
    if operation == '+':
        return a + b
    elif operation == '-':
        return a - b
    elif operation == '*':
        return a * b
    elif operation == '/':
        if b == 0:
            raise ValueError("Cannot divide by zero")
        return a / b
    else:
        raise ValueError(f"Unknown operation: {operation}")


# Tests
def test_calculator():
    assert calculator(2, 3, '+') == 5
    assert calculator(10, 5, '-') == 5
    assert calculator(4, 3, '*') == 12
    assert calculator(8, 2, '/') == 4
    print("✅ All tests passed")

if __name__ == '__main__':
    test_calculator()
`;

            setContent(mockContent);
        } catch (error) {
            setContent(`Error loading file: ${error}`);
        } finally {
            setLoading(false);
        }
    };

    const handleCopy = () => {
        navigator.clipboard.writeText(content);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleDownload = () => {
        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = fileName;
        a.click();
        URL.revokeObjectURL(url);
    };

    const getLanguage = () => {
        const ext = fileName.split('.').pop()?.toLowerCase();
        const langMap: Record<string, string> = {
            'py': 'python',
            'js': 'javascript',
            'jsx': 'jsx',
            'ts': 'typescript',
            'tsx': 'tsx',
            'html': 'html',
            'css': 'css',
            'json': 'json',
            'md': 'markdown',
            'sh': 'bash',
            'yaml': 'yaml',
            'yml': 'yaml'
        };
        return langMap[ext || ''] || 'text';
    };

    if (loading) {
        return (
            <div className="h-full flex items-center justify-center bg-gray-50">
                <div className="text-center">
                    <div className="animate-spin h-8 w-8 border-4 border-blue-500 border-t-transparent rounded-full mx-auto mb-3"></div>
                    <p className="text-gray-600">Loading file...</p>
                </div>
            </div>
        );
    }

    return (
        <div className="h-full flex flex-col bg-white">
            {/* Header */}
            <div className="flex items-center justify-between px-4 py-3 border-b border-gray-200 bg-gray-50">
                <div className="flex items-center space-x-2">
                    <Code className="h-5 w-5 text-blue-500" />
                    <div>
                        <h3 className="font-medium text-gray-900">{fileName}</h3>
                        <p className="text-xs text-gray-500">{filePath}</p>
                    </div>
                </div>

                <div className="flex items-center space-x-2">
                    <button
                        onClick={handleCopy}
                        className="flex items-center space-x-1 px-3 py-1.5 text-sm bg-white border border-gray-300 rounded hover:bg-gray-50 transition"
                    >
                        {copied ? (
                            <>
                                <Check className="h-4 w-4 text-green-500" />
                                <span>Copied!</span>
                            </>
                        ) : (
                            <>
                                <Copy className="h-4 w-4" />
                                <span>Copy</span>
                            </>
                        )}
                    </button>

                    <button
                        onClick={handleDownload}
                        className="flex items-center space-x-1 px-3 py-1.5 text-sm bg-blue-600 text-white rounded hover:bg-blue-700 transition"
                    >
                        <Download className="h-4 w-4" />
                        <span>Download</span>
                    </button>
                </div>
            </div>

            {/* Content */}
            <div className="flex-1 overflow-auto">
                <SyntaxHighlighter
                    language={getLanguage()}
                    style={vscDarkPlus}
                    showLineNumbers
                    customStyle={{
                        margin: 0,
                        padding: '1rem',
                        fontSize: '14px',
                        lineHeight: '1.5'
                    }}
                >
                    {content}
                </SyntaxHighlighter>
            </div>

            {/* Footer */}
            <div className="px-4 py-2 border-t border-gray-200 bg-gray-50 text-xs text-gray-500 flex items-center justify-between">
                <span>{content.split('\n').length} lines • {content.length} chars</span>
                <span className="px-2 py-0.5 bg-blue-100 text-blue-700 rounded">
                    {getLanguage()}
                </span>
            </div>
        </div>
    );
}
