"""
University of Juba Preliminary Pages Generator
Generates Title Page, Declaration, Approval, Dedication, Acknowledgement, Abstract.
"""
from datetime import datetime
from services.deepseek_direct import deepseek_direct_service

async def generate_preliminary_pages_uoj(
    topic: str,
    case_study: str,
    student_name: str = "[STUDENT NAME]",
    index_number: str = "[INDEX NUMBER]",
    school: str = "EDUCATION",
    department: str = "[DEPARTMENT]",
    degree: str = "EDUCATION",
    supervisor: str = "[SUPERVISOR NAME]"
) -> str:
    """Generate all UoJ preliminary pages in sequence."""
    
    current_year = datetime.now().year
    
    # 1. Title Page
    title_page = f"""
# {topic.upper()}
    
**CASE STUDY: {case_study.upper()}**

**BY**

**{student_name.upper()}**
**{index_number.upper()}**

**A RESEARCH DISSERTATION SUBMITTED TO THE SCHOOL OF {school.upper()}, DEPARTMENT OF {department.upper()}, UNIVERSITY OF JUBA IN PARTIAL FULFILLMENT OF THE REQUIREMENTS FOR THE AWARD OF THE DEGREE OF BACHELOR OF {degree.upper()}.**

**{datetime.now().strftime('%B, %Y').upper()}**
"""

    # 2. Declaration
    declaration = f"""
# DECLARATION

I, **{student_name}**, declare that this research dissertation is my original work and has never been submitted for a degree in any other University.

**Signature**: ______________________    **Date**: ______________________

**{student_name}**
"""

    # 3. Approval
    approval = f"""
# APPROVAL

This research dissertation titled "**{topic.upper()}**" has been submitted with my approval as the University Supervisor.

**Signature**: ______________________    **Date**: ______________________

**{supervisor}**
**(Supervisor)**
Department of {department}
School of {school}
University of Juba
"""

    # 4. Dedication (Generated)
    dedication_prompt = f"Write a short, heartfelt dedication for a thesis about {topic}. Dedicate to parents, family, and friends. One paragraph."
    dedication_text = await deepseek_direct_service.generate_content(dedication_prompt, max_tokens=150)
    
    dedication = f"""
# DEDICATION

{dedication_text}
"""

    # 5. Acknowledgement (Generated)
    ack_prompt = f"Write a formal acknowledgement for a thesis about {topic} at University of Juba. Acknowledge God, Supervisor {supervisor}, University staff, family, and participants. One paragraph."
    ack_text = await deepseek_direct_service.generate_content(ack_prompt, max_tokens=250)
    
    acknowledgement = f"""
# ACKNOWLEDGEMENT

{ack_text}
"""

    # 6. Abstract (Placeholder or Generated Draft)
    # Since mostly parallel, we generate a generic abstract structure here
    abstract_prompt = f"""Write a generic Abstract for a study about {topic} in {case_study}. 
    Structure: Purpose, Methodology (Quantitative), and 'Findings revealed that...' (make generic positive findings). 
    Conclusion: 'The study recommends that...'
    One block paragraph."""
    abstract_text = await deepseek_direct_service.generate_content(abstract_prompt, max_tokens=300)
    
    abstract = f"""
# ABSTRACT

{abstract_text}
"""

    # 7. Table of Contents (Placeholder - usually auto-generated by text processors)
    toc = """
# TABLE OF CONTENTS

(To be auto-generated based on final page numbers)

Title Page ................................................................. i
Declaration ................................................................ ii
Approval ................................................................... iii
Dedication ................................................................. iv
Acknowledgement ............................................................ v
Abstract ................................................................... vi
Table of Contents .......................................................... vii
"""

    # Combined
    return f"{title_page}\n<div style='page-break-after: always;'></div>\n{declaration}\n<div style='page-break-after: always;'></div>\n{approval}\n<div style='page-break-after: always;'></div>\n{dedication}\n<div style='page-break-after: always;'></div>\n{acknowledgement}\n<div style='page-break-after: always;'></div>\n{abstract}\n<div style='page-break-after: always;'></div>\n{toc}\n<div style='page-break-after: always;'></div>\n"
